from tkinter import *
def click(event):
    global scvalue
    text = event.widget.cget("text")
    print(text)
    if text=="=":
        if scvalue.get().isdigit():
            value = int(scvalue.get())
        else:
            value = eval(screen.get())
        scvalue.set(value)
        screen.update()
    elif text=="C":
        scvalue.set("")
        screen.update
    else:
        scvalue.set(scvalue.get()+text)
        screen.update()
root = Tk()
root.geometry("444x900")
root.title("Simple Calculator by Yash")
scvalue = StringVar()
scvalue.set("")
screen = Entry(root,textvar=scvalue,font="lucida 40 bold",bg="skyblue")
screen.pack(fill=X, ipadx=8, pady=10, padx=10)
f = Frame(root,bg="skyblue")
b=Button(f,text="9",padx = 1, pady = 2, width = 2,font="lucida 35 bold")
b.bind("<Button-1>",click)
b.pack(side = LEFT,padx = 18,pady=5)
b=Button(f,text="8",padx = 1, pady = 2,width=2,font="lucida 35 bold")
b.bind("<Button-1>",click)
b.pack(side = LEFT,padx = 18,pady=5)
b=Button(f,text="7",padx = 1, pady = 2,width=2,font="lucida 35 bold")
b.bind("<Button-1>",click)
b.pack(side = LEFT,padx = 18,pady=5)
f.pack()
f = Frame(root,bg="skyblue")
b=Button(f,text="6",padx = 1, pady = 2,width=2,font="lucida 35 bold")
b.bind("<Button-1>",click)
b.pack(side = LEFT,padx = 18,pady=5)
b=Button(f,text="5",padx = 1, pady = 2,width=2,font="lucida 35 bold")
b.bind("<Button-1>",click)
b.pack(side = LEFT,padx = 18,pady=5)
b=Button(f,text="4",padx = 1,pady = 1,width=2,font="lucida 35 bold")
b.bind("<Button-1>",click)
b.pack(side = LEFT,padx = 18,pady=5)
f.pack()
f = Frame(root,bg="skyblue")
b=Button(f,text="3",padx = 1, pady = 2,width=2,font="lucida 35 bold")
b.bind("<Button-1>",click)
b.pack(side = LEFT,padx = 18,pady=5)
b=Button(f,text="2",padx = 1, pady = 2,width=2,font="lucida 35 bold")
b.bind("<Button-1>",click)
b.pack(side = LEFT,padx = 18,pady=5)
b=Button(f,text="1",padx = 1, pady = 2,width=2,font="lucida 35 bold")
b.bind("<Button-1>",click)
b.pack(side = LEFT,padx = 18,pady=5)
f.pack()
f = Frame(root,bg="skyblue")
b=Button(f,text="+",padx = 1, pady = 2,width=2,font="lucida 35 bold",bg="lightgreen")
b.bind("<Button-1>",click)
b.pack(side = LEFT,padx = 18,pady=5)
b=Button(f,text="0",padx = 1, pady = 2,width=2,font="lucida 35 bold")
b.bind("<Button-1>",click)
b.pack(side = LEFT,padx = 18,pady=5)
b=Button(f,text="-",padx = 1, pady = 2,width=2,font="lucida 35 bold",bg="lightgreen")
b.bind("<Button-1>",click)
b.pack(side = LEFT,padx = 18,pady=5)
f.pack()
f = Frame(root,bg="skyblue")
b=Button(f,text="/",padx = 1, pady = 2,width=2,font="lucida 35 bold",bg="lightgreen")
b.bind("<Button-1>",click)
b.pack(side = LEFT,padx = 18,pady=5)
b=Button(f,text="C",padx = 1, pady = 2,width=2,font="lucida 35 bold")
b.bind("<Button-1>",click)
b.pack(side = LEFT,padx = 18,pady=5)
b=Button(f,text="=",padx = 1, pady = 2,width=2,font="lucida 35 bold",bg="lightgreen")
b.bind("<Button-1>",click)
b.pack(side = LEFT,padx = 18,pady=5)
f.pack()
f = Frame(root,bg="skyblue")
b=Button(f,text="%",padx = 1, pady = 2,width=2,font="lucida 35 bold",bg="lightgreen")
b.bind("<Button-1>",click)
b.pack(side = LEFT,padx = 18,pady=5)
b=Button(f,text="*",padx = 1, pady = 2,width=2,font="lucida 35 bold",bg="lightgreen")
b.bind("<Button-1>",click)
b.pack(side = LEFT,padx = 18,pady=5)
f.pack()
b=Button(f,text=".",padx = 1, pady = 2,width=2,font="lucida 35 bold",bg="lightgreen")
b.bind("<Button-1>",click)
b.pack(side = LEFT,padx = 18,pady=5)
f.pack()
root.mainloop()
